language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  app:  floating-shore-49279 # optional if it's the same as your repo name
  api_key: "6dbb6d83-cd7d-44de-b528-048a76b0c066"
script: 
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake