language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  app:  floating-shore-49279 # optional if it's the same as your repo name
  api_key: "6dbb6d83-cd7d-44de-b528-048a76b0c066"
script: 
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake
addons:
  code_climate:
    repo_token: 9d370d609b46c32d3e0ee4b5d1b447782583439638d59f7d70822b16d3ee3d8e
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter