# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4e817ce7f9b1a5bcae824dde3478dd0235229896a91531717d4a3ede9d822b12877c8272524ffc66afc7ad23796dee7f465c81347076f8a2802ab36703bad3
  

test:
  secret_key_base: 12038c7be9dea40b416fd2312cb843e158d6c580e033ccd31420185c7fe41a05493336cd503359839761306359d2153af922af8a07554ca5da907c3f77fd7bf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
